framework:
    default_locale: 'fr' # la langue par défaut de votre application
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'fr' # la langue qui sera utilisée si la traduction n'est pas disponible dans la langue de l'utilisateur
