# ------------------------- générale -----------------------
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ------------------------- products -----------------------

products_list:
    path: /products
    controller: App\Controller\ProductController::getAllProducts
    methods: GET

product_selection:
    path: /products/{id}
    controller: App\Controller\ProductController::getProduct
    methods: GET

lastvideos:
    path: /
    controller: App\Controller\ProduitsController::lastVideos
    methods: GET

best_products:
    path: /best
    controller: App\Controller\ProduitsController::bestProducts
    methods: GET

# -------------------------- vendeur ------------------------
    
vendeur:
    path: /vendeur
    controller: App\Controller\ProduitsController::vendeur
    methods: POST

vendeur_list:
    path: /vendeur-list
    controller: App\Controller\ProduitsController::getProductBuyer
    methods: GET

vendeur_modifier:
    path: /vendeur-modifier/{id}
    controller: App\Controller\ProduitsController::alterProduct
    methods: PUT

vendeur_delete:
    path: /vendeur-delete/{id}
    controller: App\Controller\ProduitsController::deleteProduct
    methods: DELETE

# ------------------------- product catégories -----------------------

categories_list:
    path: /categories
    controller: App\Controller\ProduitsController::getCategories
    methods: GET

products_categories_list:
    path: /categories/prod/{id}
    controller: App\Controller\ProduitsController::CategoriesProduit
    methods: GET

send_categories:
    path: /sendCategories/{id}
    controller: App\Controller\ProduitsController::CategoriesName
    methods: GET

# ------------------------- users -----------------------

login:
    path: /login
    controller: App\Controller\UsersController::login
    methods: POST

logout:
    path: /logout
    controller: App\Controller\UsersController::logout
    methods: POST

register:
    path: /register
    controller: App\Controller\UsersController::register
    methods: POST

# ------------------------- panier -----------------------

panier_getAllPanierItems:
    path: /panier
    controller: App\Controller\PanierController::getAllPanierItems
    methods: GET
    
panier_num:
    path: /panier/{userid}
    controller: App\Controller\PanierController::getQuantity
    methods: GET

panier_ajouter:
    path: /panier/add
    controller: App\Controller\PanierController::ajouterAuPanier
    methods: POST

panier_supprimer:
    path: /panier/delete/{id}
    controller: App\Controller\PanierController::supprimerDuPanier
    methods: DELETE

panier_update:
    path: /panier/modifier
    controller: App\Controller\PanierController::updatePanier
    methods: PUT

# ------------------------- profil -----------------------

profil_modifier:
    path: /profil
    controller: App\Controller\ProfilController::modifierInformations
    methods: PUT

profil_get:
    path: /profil
    controller: App\Controller\ProfilController::getProfilData
    methods: GET

profil_upload_image:
    path: /profil
    controller: App\Controller\ProfilController::uploadImage
    methods: POST

# ------------------------- profil-public -----------------------

public_profil_user:
    path: /profil-public/user/{id}
    controller: App\Controller\ProfilController::publicProfilData
    methods: GET

public_profil_get_product:
    path: /profil-public/{id}
    controller: App\Controller\ProfilController::getProduct
    methods: GET

# ------------------------- commande -----------------------

getCommand:
    path: /getCommand
    controller: App\Controller\PanierController::getCommand
    methods: GET

command:
    path: /command
    controller: App\Controller\PanierController::command
    methods: POST

updateCommand:
    path: /command/modifier
    controller: App\Controller\PanierController::updateCommand
    methods: PUT

command_delete:
    path: /command/{id}
    controller: App\Controller\PanierController::deleteCommand
    methods: DELETE

# ------------------------- chat -----------------------

chat:
    path: /chat
    controller: App\Controller\ChatController::getChat
    methods: GET

chat_annuler:
    path: /chat/{id}/annuler
    controller: App\Controller\ChatController::annulerChat
    methods: DELETE

# ------------------------- contact -----------------------

contact:
    path: /contact
    controller: App\Controller\ContactController::contact
    methods: POST

# ------------------------- avis -----------------------

get_avis:
    path: /produit-detail/{id}
    controller: App\Controller\AvisController::getAvis
    methods: GET

create_avis:
    path: /produit-detail/{id}
    controller: App\Controller\AvisController::createAvis
    methods: POST

record_action:
    path: /produit-detail/{id}
    controller: App\Controller\AvisController::recordAction
    methods: PUT

# ------------------------- like -----------------------

create_like:
    path: /produit-detail/{id}/like
    controller: App\Controller\AvisController::createLike
    methods: POST

avis_like:
    path: /produit-detail/{id}/like
    controller: App\Controller\AvisController::getLike
    methods: GET

# ------------------------- Favoris -----------------------

ajouter_favoris:
    path: /favoris/ajouter
    controller: App\Controller\FavorisController::ajouterFavoris
    methods: POST

supprimer_favoris:
    path: /favoris/supprimer
    controller: App\Controller\FavorisController::deleteFavoris
    methods: DELETE

supprimer_tous_favoris:
    path: /favoris/supprimer-tous/{userid}
    controller: App\Controller\FavorisController::deleteAll
    methods: DELETE

get_favoris:
    path: /favoris/{id}/{userid}/liste
    controller: App\Controller\FavorisController::getFavoris
    methods: GET

get_all_favoris:
    path: /favoris/all/{id}
    controller: App\Controller\FavorisController::getAllFavorisUser
    methods: GET

# ------------------------- Promos -----------------------

get_promos:
    path: /promos/{id}
    controller: App\Controller\PromosController::getPromos
    methods: GET