controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

products_list:
    path: /products
    controller: App\Controller\ProductController::getAllProducts
    methods: GET

product_selection:
    path: /products/{id}
    controller: App\Controller\ProductController::getProduct
    methods: GET

product_creation:
    path: /products
    controller: App\Controller\ProductController::createNewProduct
    methods: POST

product_deletion:
    path: /products/{id}
    controller: App\Controller\ProductController::deleteProduct
    methods: DELETE

product_modification:
    path: /products/{id}
    controller: App\Controller\ProductController::alterProduct
    methods: PUT

login:
    path: /login
    controller: App\Controller\UsersController::login
    methods: POST

logout:
    path: /logout
    controller: App\Controller\UsersController::logout
    methods: POST

register:
    path: /register
    controller: App\Controller\UsersController::register
    methods: POST

panier_getAllPanierItems:
    path: /panier
    controller: App\Controller\PanierController::getAllPanierItems
    methods: GET

panier_ajouter:
    path: /panier/add
    controller: App\Controller\PanierController::ajouterAuPanier
    methods: POST

panier_supprimer:
    path: /panier/delete/{id}
    controller: App\Controller\PanierController::supprimerDuPanier
    methods: DELETE

profil_modifier:
    path: /profil
    controller: App\Controller\ProfilController::modifierInformations
    methods: PUT

profil_get:
    path: /profil
    controller: App\Controller\ProfilController::getProfilData
    methods: GET

profil_upload_image:
    path: /profil
    controller: App\Controller\ProfilController::uploadImage
    methods: POST

commandes:
    path: /commandes
    controller: App\Controller\CommandeController::getCommandes
    methods: GET

commande_annuler:
    path: /commandes/{id}/annuler
    controller: App\Controller\CommandeController::annulerCommande
    methods: DELETE

chat:
    path: /chat
    controller: App\Controller\ChatController::getChat
    methods: GET

chat_annuler:
    path: /chat/{id}/annuler
    controller: App\Controller\ChatController::annulerChat
    methods: DELETE

categories_list:
    path: /categories
    controller: App\Controller\ProduitsController::getCategories
    methods: GET

products_categories_list:
    path: /categories/prod/{id}
    controller: App\Controller\ProduitsController::CategoriesProduit
    methods: GET

send_categories:
    path: /sendCategories/{id}
    controller: App\Controller\ProduitsController::CategoriesName
    methods: GET

contact:
    path: /contact
    controller: App\Controller\ContactController::contact
    methods: POST

lastvideos:
    path: /
    controller: App\Controller\ProduitsController::lastVideos
    methods: GET

vendeur:
    path: /vendeur
    controller: App\Controller\VendeurController::vendeur
    methods: POST

vendeur_list:
    path: /vendeur-list
    controller: App\Controller\VendeurController::getProductBuyer
    methods: GET

avis_get:
    path: /produit-detail/{id}
    controller: App\Controller\AvisController::getAvisForProduc
    methods: GET

avis_create:
    path: /produit-detail/{id}/avis-create
    controller: App\Controller\AvisController::createAvis
    methods: POST

avis_record_action:
    path: /produit-detail/{id}/record-action
    controller: App\Controller\AvisController::recordAction
    methods: POST

avis_note:
    path: /produit-detail/{id}/avis-note
    controller: App\Controller\AvisController::saveNote
    methods: POST
    